#!/bin/bash

# USE AT YOUR OWN RISK!!!
# usb_remount - version 1.0.1


IFS=$'\n'

if [ $( mount | grep -v mounted | grep read-only -c ) -eq 0 ]; then
    echo "no read-only devices were detected"
    exit
fi

for mnt in $( mount | grep read-only | grep -v mounted ); do

    src_dev=$( echo $mnt | awk {'print $1'} )
    tgt_dev=$( df | grep $src_dev | grep -o '\/Volume.*' )
    fs=$( mount | grep $src_dev | awk -F"(" {'print $2'} | awk -F"," {'print $1'} )

    idf=$( echo $src_dev | awk -F'/' {'print $3'} )
    if [ $( system_profiler SPUSBDataType 2>/dev/null | grep -c $idf ) -eq 0 ]; then
        continue
    fi

    sudo diskutil unmount $src_dev
    sudo mkdir -p "$tgt_dev"
    sudo mount -t $fs $src_dev "$tgt_dev"

    ret=$?
    if [ $ret -ne 0 ]; then
        echo "re-mount error: mount -t $fs $src_dev $tgt_dev"
        echo "return: $ret"
    else
        echo "mount $src_dev on $tgt_dev successfully"
    fi

done

#mount
